### ISSUE TITLE
Loads endlessly in 1.21

### ISSUE THREAD

**Issue by chrisp50** [raspberrygitq/Animated-Ore#2]
Minecraft loads endlessly when trying to load the Animated Ore 0.4.1 Minecraft Resource Pack.

**Comment by raspberrygitq** [comment]
Hi, I tried to reproduce your problem on Minecraft 1.21 (vanilla) without any modifications and it loaded the resource pack normally. Are you using a modified Minecraft 1.21? If so could you send a screenshot of the modification folder?
