### ISSUE TITLE
Could you add support for Oritech Ores please?

### ISSUE THREAD

**Issue by sam-snyder** [raspberrygitq/Animated-Ore#3]
As title asks.. pretty please with a cherry on top?

**Comment by raspberrygitq** [comment]
The work is in progress.  Please wait.

**Comment by raspberrygitq** [comment]
Hi again, does the stuff with the following name `resource_node_****` occur naturally in the world?

**Comment by sam-snyder** [comment]
> The work is in progress... Please wait.

yay!

> Hi again, does the stuff with the following name `resource_node_****` occur naturally in the world?

I havent come across it yet so I'm not sure.

**Comment by raspberrygitq** [comment]
Hi, support for Oritech has been introduced. https://github.com/raspberrygitq/Animated-Ore/commit/44297fdb7a8e596f22d84f19c8548af3a3c02aec

You can download from the source code and check that it has no bugs and that everything works. It will be released soon on Modrinth

**Comment by sam-snyder** [comment]
Amazing! Thank you!
