### ISSUE TITLE
Deeper and Darker Texture issue

### ISSUE THREAD

**Issue by UnKZero** [raspberrygitq/Animated-Ore#4]
Ore textures sometimes work but mostly not

![New World (1)](https://github.com/user-attachments/assets/c002d363-dbd8-45eb-a422-3ebaec0f9463)

(Same Ore in image)

Removing the compat folder fixes the issue but obviously the deeper and darker ores become normal

**Comment by raspberrygitq** [comment]
Hi, the bug with Deeper and Darker textures has been fixed. https://github.com/raspberrygitq/Animated-Ore/commit/460fe6764a6c20c603ea9bc8dc691ba00748ad35

![image](https://github.com/user-attachments/assets/b0b378f4-b9bd-427f-9373-10d9b4c80df9)

Animated Ore version 0.5.5 fixes this problem. It has already been uploaded to Modrinth.

Thank you for reporting the problem! 😊
