### ISSUE TITLE
Mekanism support?

### ISSUE THREAD

**Issue by JohnGoten** [raspberrygitq/Animated-Ore#6]
A relatively simple ask (please <3) for the 5 total ore types (+another 5 as deepslate variants exist for all of them)
Left to right (running Mekanism 10.7.8 in MC version 1.21.1)
Tin > Osmium > Uranium > Flourite > Lead
![image](https://github.com/user-attachments/assets/86431f8b-6689-47bb-9770-b0ccc5624e97)

Tin, Osmium and Flourite sure are more or less Iron level
Uranium could glow similarly to Lapis Lazuli
Lead I am uncertain of, could be like most of the other ones as well

was a little confused as to why such a popular one wasn't yet addressed but maybe now that it is christmas of all times, perhaps a good time to change that (:

**Comment by raspberrygitq** [comment]
Hi! Sorry I'm only replying now, but I didn't get a notification. It's still Christmas, but I'll take that suggestion into consideration.

Merry Christmas! 🎅

Best regards, @raspberrygitq

**Comment by raspberrygitq** [comment]
Hi, support for Mekanism was released with the Animated Ore 0.6.2 version.
